### ISSUE TITLE
don't work with bootstrap

### ISSUE THREAD

**Issue by morsiiii** [lukaszfiszer/selectnav.js#4]
hello plz i wanted to use selectnav with bootstrap, i've removed the collapse menu and added the script and everything but its not showing, plz any help?

**Comment by lukaszfiszer** [comment]
It's in fact a general bug, not a Bootstrap related one. The script was simply crashing when encountering empty links (on those are in fact used by Bootstrap for dividers). It is fixed now

You can also check out the demo showing the integration of selectnav with boostrap - http://jsbin.com/uwivar/2/edit.

**Comment by morsiiii** [comment]
thanks you for your time, works perfect now : )
Thanks too much lukaszfiszer

**Comment by davidpanzarella** [comment]
This still doesn't seem to work right. If i use SelectNav with BS 2.3, and try to add a collapse, all tabs stay open initially, and don't toggle, but rather each element toggles, which is the incorrect behavior. The "in" class gets applied to each element. Furthermore, BS has to be applied after selectNav is, otherwise there are errors. Do you have a workaround?

**Comment by davidpanzarella** [comment]
Anyone get a fix for this?
